# Generated by Django 5.2.11 on 2026-03-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
