# Generated by Django 5.2.11 on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='bill_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
    ]
