# Generated by Django 5.2.11 on 2026-03-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_sale_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_permissions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
