# Generated by Django 5.2.11 on 2026-03-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_purchase_selling_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='costing_method',
            field=models.CharField(choices=[('average', 'Average'), ('fifo', 'FIFO')], default='average', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
