# Generated by Django 5.2.11 on 2026-03-26 10:55

from django.db import migrations, models


def initialize_discount_fields(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    Purchase = apps.get_model('inventory', 'Purchase')
    Product.objects.all().update(full_price=models.F('sale_price'), discount_percent=0)
    Purchase.objects.all().update(full_selling_price=models.F('selling_price'), discount_percent=0)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_sale_costing_method_sale_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchase',
            name='full_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(initialize_discount_fields, migrations.RunPython.noop),
    ]
