# Generated by Django 5.2.11 on 2026-03-30 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_sale_discount_amount_voucher_sale_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='specific_customer',
            field=models.CharField(blank=True, default='', help_text='Only valid for this customer name (case-insensitive)', max_length=200),
        ),
        migrations.AddField(
            model_name='voucher',
            name='specific_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='inventory.product'),
        ),
    ]
