# Generated by Django 5.2.11 on 2026-03-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_voucher_specific_customer_voucher_specific_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (capital) for percentage vouchers', max_digits=10, null=True),
        ),
    ]
